"""Split input into DI and reference keys

Revision ID: a4b8d3fbc5eb
Revises: b87f775e8443
Create Date: 2026-06-27 17:45:51.501501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b8d3fbc5eb'
down_revision: Union[str, Sequence[str], None] = 'b87f775e8443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('di_s3_key', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('reference_s3_key', sa.String(), nullable=True))
    op.drop_column('jobs', 'input_s3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('input_s3_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'reference_s3_key')
    op.drop_column('jobs', 'di_s3_key')
    # ### end Alembic commands ###
